//
// Created by netcan on 2021/06/28.
//

#ifndef CONFIG_LOADER_CONFIGLOADERNS_H
#define CONFIG_LOADER_CONFIGLOADERNS_H

#define CONFIG_LOADER_NS config_loader
#define CONFIG_LOADER_NS_BEGIN namespace CONFIG_LOADER_NS {
#define CONFIG_LOADER_NS_END }

#endif //CONFIG_LOADER_CONFIGLOADERNS_H
